name: Python application test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover -s src/tests
    - name: Compress Lambda function
      run: |
        zip -r lambda_function.zip src/*
    - name: Upload to S3
      uses: aws-actions/aws-s3-sync@v3
      with:
        source: .
        destination: s3://your-bucket-name/lambda_function.zip
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
