on:
  push:
      branches: [dev, master]

name: Lambda ECR Deployment

jobs:
  deploy:
      if: github.ref == 'refs/heads/dev'
      name: Deploy to ECR and update Lambda
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push the image to Amazon ECR
            id: build-image
            run: |
                # Build a docker container and push it to ECR 
                echo "Registry: ${{ vars.ECR_REGISTRY }}"
                aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REGISTRY }}
                docker build -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest .
                echo "Pushing image to ECR..."
                docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest
                echo "name=image::${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest" >> $GITHUB_OUTPUT

          - name: Update AWS Lambda function
            id: update-lambda
            run: |
              aws lambda update-function-code --function-name lambda_cliente --image-uri 470692656758.dkr.ecr.us-east-1.amazonaws.com/pos_tech_fiap:latest
